/**
 * Shared memory types — used by the Node memory server and the React client.
 */

/** Where a memory originated */
export type MemoryCategory =
  | 'journal'
  | 'soccer_training'
  | 'match_report'
  | 'goal'
  | 'task'
  | 'college_application'
  | 'activity'
  | 'project'
  | 'ai_summary'
  | 'user_note'
  | 'document'

export const MEMORY_CATEGORIES: MemoryCategory[] = [
  'journal',
  'soccer_training',
  'match_report',
  'goal',
  'task',
  'college_application',
  'activity',
  'project',
  'ai_summary',
  'user_note',
  'document',
]

/** Full memory record including vector embedding */
export interface Memory {
  id: string
  category: MemoryCategory
  title: string
  text: string
  importance: number
  createdAt: string
  /** Optional link to Supabase or local source record */
  sourceId?: string | null
  embedding: number[]
}

/** Input when creating a memory (embedding generated by EmbeddingService) */
export interface CreateMemoryInput {
  id?: string
  category: MemoryCategory
  title: string
  text: string
  importance: number
  createdAt?: string
  sourceId?: string | null
}

/** Memory returned to the AI — no embedding payload */
export interface RetrievedMemory {
  id: string
  category: MemoryCategory
  title: string
  text: string
  importance: number
  createdAt: string
  similarity: number
  recencyScore: number
  combinedScore: number
}

export interface RetrieveOptions {
  limit?: number
  categories?: MemoryCategory[]
  minScore?: number
}

export interface RetrieveResult {
  query: string
  memories: RetrievedMemory[]
  contextBlock: string
}

export interface MemoryServerConfig {
  dbPath: string
  ollamaBaseUrl: string
  embeddingModel: string
  port: number
}

export const DEFAULT_MEMORY_CONFIG: MemoryServerConfig = {
  dbPath: 'data/seldom-memory.db',
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  embeddingModel: 'nomic-embed-text',
  port: 3847,
}

export const RETRIEVAL_WEIGHTS = {
  similarity: 0.6,
  importance: 0.25,
  recency: 0.15,
} as const
